ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("ecommerceapp.urls")),
    path('captcha/', include('captcha.urls')),  # Add this

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerceapp/urls.py
from django.urls import path
from .views import *
from . import views


app_name = "ecommerceapp"

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("about/", AboutView.as_view(), name="about"),
    path("contact/", ContactView.as_view(), name="contact"),
    path("shops/", ShopsView.as_view(), name="shops"),
    path("product/<slug:slug>", ProductDetailView.as_view(), name="productdetail"),

    path("addtocart/<int:pro_id>/", AddToCartView.as_view(), name="addtocart"),
    path("my-cart/", MyCartView.as_view(), name="mycart"),
    path("manage-cart/<int:cp_id>/", ManageCartView.as_view(), name="managecart"),
    path("empty-cart/", EmptyCartView.as_view(), name="emptycart"),

    path("checkout/", CheckoutView.as_view(), name="checkout"),
    path("paystack-request/<int:order_id>/", PaystackRequestView.as_view(), name="paystackrequest"),
    path("paystack-webhook/", PaystackWebhookView.as_view(), name="paystack-webhook"),
    path("paystack-verify/", PaystackVerifyView.as_view(), name="paystack-verify"),

    path("register/", CustomerRegistrationView.as_view(), name="customerregistration"),
    
    path("logout/", CustomerLogoutView.as_view(), name="customerlogout"),
    path("login/", CustomerLoginView.as_view(), name="customerlogin"),


    path("profile/", CustomerProfileView.as_view(), name="customerprofile"),
    path("profile/order-<int:pk>/", CustomerOrderDetailView.as_view(), name="customerorderdetail"),
    
    path("profile/edit/", CustomerProfileEditView.as_view(), name="customerprofile_edit"),

    path('change_password/', views.change_password, name='change_password'),


    path("search/", SearchView.as_view(), name="search"),

    path("forgot-password/", PasswordForgotView.as_view(), name="passwordforgot"),
    path("password-reset/<email>/<token>/", PasswordResetView.as_view(), name="passwordreset"),

    # Admin Side pages

    path("admin-login/", AdminLoginView.as_view(), name="adminlogin"),
    path("admin-home/", AdminHomeView.as_view(), name="adminhome"),
    path("admin-order/<int:pk>/", AdminOrderDetailView.as_view(), name="adminorderdetail"),
    path("admin-all-orders/", AdminOrderListView.as_view(), name="adminorderlist"),

    path("admin-order/<int:pk>-change/", AdminOrderStatusChangeView.as_view(), name="adminorderstatuschange"),

    path("admin-product/list/", AdminProductListView.as_view(), name="adminproductlist"),
    path("admin-product/add/", AdminProductCreateView.as_view(), name="adminproductcreate"),
]

templates/adminpages/adminbase.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <title>
    {% block title %} {% endblock title %}
  </title>
  <meta content="ecommerce website we deliver products in 1 hours" name="description">
  <meta content="ecommerce" name="amazon,flipkart,selling,products">


  <!-- Google Fonts -->
  <link
    href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
    rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static '/assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static '/assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static '/assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static '/assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static '/assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static '/assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static '/assets/css/style.css' %}" rel="stylesheet">


  {% comment %} <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"> {% endcomment %}

</head>

<body>
  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top bg-dark">
    <div class="container d-flex align-items-center justify-content-between">

      <a href="/" class="logo text-white">YARN_ME</a>


      <nav id="navbar" class="navbar">
        <ul>
          <li><a class="nav-link scrollto active" href="{% url 'ecommerceapp:adminhome' %}">Home</a></li>
          <li><a class="nav-link scrollto" href="{% url 'ecommerceapp:adminorderlist' %}">All Orders</a></li>
          <li><a class="nav-link scrollto" href="{% url 'ecommerceapp:adminproductlist' %}">All Products</a></li>
          <li><a class="nav-link scrollto" href="{% url 'ecommerceapp:index' %}" target="_blank">View site</a></li>

        
    </ul>
    <i class="bi bi-list mobile-nav-toggle"></i>
  </nav><!-- .navbar -->

</div>
</header><!-- End Header -->





    {% comment %} <section id="hero">
      <div class="hero-container">
  
        {% block content %}
  
  
  
  
  
  
        {% endblock content %}
  
      </div>
    </section><!-- End Hero --> {% endcomment %}
  
    <main id="main">
  
      {% block body %}
  
  
  
  
  
  
  
      {% endblock body %}
  
    </main><!-- End #main -->
  
   <!-- ======= Footer ======= -->
   <footer id="footer">
  
    <div class="footer-top">
      <div class="container">
        <div class="row">
  
          <div class="col-lg-3 col-md-6 footer-contact">
            <h3>Yarn_me</h3>
            <p>
              <strong>Phone:</strong> +1 5589 55488 55<br>
              <strong>Email:</strong> info@example.com<br>
            </p>
          </div>
  
          <div class="col-lg-2 col-md-6 footer-links">
            <h4>Useful Links</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'ecommerceapp:index' %}">Home</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'ecommerceapp:shops' %}">Shop</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'ecommerceapp:about' %}">About</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Terms of service</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Privacy policy</a></li>
            </ul>
          </div>
  
          <div class="col-lg-3 col-md-6 footer-newsletter">
            <h4>Join Our Newsletter</h4>
            <form action="" method="post">
              <input type="email" name="email"><input type="submit" value="Subscribe">
            </form>
          </div>
  
        </div>
      </div>
    </div>
  
    <div class="container d-md-flex py-4">
  
      <div class="me-md-auto text-center text-md-start">
        <div class="copyright">
          &copy; Copyright <strong><span>Yarn_me</span></strong>. All Rights Reserved
        </div>
        <div class="credits">
          <!-- All the links in the footer should remain intact. -->
          <!-- You can delete the links only if you purchased the pro version. -->
          <!-- Licensing information: https://bootstrapmade.com/license/ -->
          <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/tempo-free-onepage-bootstrap-theme/ -->
          Designed by <a href="/">Gucci</a>
        </div>
      </div>
      <div class="social-links text-center text-md-right pt-3 pt-md-0">
        <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
        <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
        <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
        <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
        <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
      </div>
    </div>
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
    class="bi bi-arrow-up-short"></i></a>

<!-- Vendor JS Files -->
<script src="{% static '/assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static '/assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
<script src="{% static '/assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
<script src="{% static '/assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
<script src="{% static '/assets/vendor/php-email-form/validate.js' %}"></script>

<!-- Template Main JS File -->
<script src="{% static '/assets/js/main.js' %}"></script>


{% block script %}

{% endblock script %}

</body>
</html>

templates/adminpages/adminhome.html
{% extends "adminpages/adminbase.html" %}

{% block title %} Admin Home{% endblock title %}

{% block body %}
<section class="bg-secondary" style="height: 200px;">

</section>
<div class="card shadow-lg border-0 bg-light m-5 p-5">
    <div class="row">
        <div class="col-md-8 mx-auto">
            <h4>Pending Orders</h4>
            <table class="table">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Order ID</th>
                        <th>Customer</th>
                        <th>Ordered On</th>
                        <th>Amount</th>
                    </tr>
                </thead>
                <tbody>
                    {% for order in pendingorders %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td><a href="{% url 'ecommerceapp:adminorderdetail' order.id %}">#ORDER_{{order.id}}</a></td>
                        <td>{{order.ordered_by}}</td>
                        <td>{{order.created_at}}</td>
                        <td>NGN.{{order.total}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock body %}

templates/adminpages/adminlogin.html
{% extends "base.html" %}

{% block title %}Admin Login{% endblock title %}

{% block body %}
<section class="bg-secondary" style="height: 200px;">

</section>
<style>
    .errorlist{
        color: red;
    }
</style>
<div class="card shadow-lg border-0 bg-light m-5 p-5">
            <h3>Admin Login Form</h3>
            <form action="" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button class="btn btn-success">Login as a Admin</button>
                {% if error %}
                <li style="color: red;">{{error}}</li>
                {% endif %}
            </form>
</div>

{% endblock body %}

templates/adminpages/adminorderdetail.html
{% extends "adminpages/adminbase.html" %}
{% load humanize %}
{% block title %}Order Detail{% endblock title %}

{% block body %}
<section class="bg-secondary" style="height: 200px;">

</section>

<div class="card shadow-lg border-0 bg-light m-5 p-5">
    <div class="row">
        <div class="col-md-8 mx-auto">
            <h3 class="fw-bold">Order Detail</h3> <hr>
    <p><span class="font-weight-bold">Order ID: </span> #ORDER_{{ord_obj.id}}</p>
    <p><span class="font-weight-bold">Order Status: </span>{{ord_obj.order_status}}</p>
    <p><span class="font-weight-bold">Order On: </span>{{ord_obj.created_at}}({{ord_obj.created_at|timesince}} ago)</p>
    <p><span class="font-weight-bold">Customer Information: </span> By {{ord_obj.ordered_by}}, {{ord_obj.mobile}}</p>
    <p><span class="font-weight-bold">Shipping Address: </span> By {{ord_obj.shipping_address}}, {{ord_obj.email}}</p>

    <h4>Ordered Items</h4>
    <table class="table">
        <thead>
            <tr>
                <th>SN</th>
                <th>Item</th>
                <th>Rate</th>
                <th>Quantity</th>
                <th>Subtotal</th>
            </tr>
        </thead>
        <tbody>
            {% for cp in ord_obj.cart.cartproducts.all %}
            <tr>
                <td>{{forloop.counter}}</td>
                <td><a href="{% url 'ecommerceapp:productdetail' cp.product.slug %}">{{cp.product.title}}({{cp.product.id}})</a></td>
                <td>{{cp.rate}}</td>
                <td>{{cp.quantity}}</td>
                <td>{{cp.subtotal}}</td>
            </tr>
            {% endfor %}
            <tr>
                <th colspan="4" class="text-right">Total:</th>
                <th> {{ord_obj.total|intcomma}}/-</th>
            </tr>
        </tbody>
    </table>
        <form action="{% url 'ecommerceapp:adminorderstatuschange' ord_obj.id %}" method="POST">
            {% csrf_token %}
            <select name="status">
                {% for i, j in allstatus %}
                <option value="{{i}}" {% if i == ord_obj.order_status %}selected{% endif %}>{{j}}</option>
                {% endfor %}
            </select>
            <button class="btn btn-success">Change</button>
        </form>
        </div>
    </div>
</div>
{% endblock body %}

templates/adminpages/adminorderlist.html
{% extends "adminpages/adminbase.html" %}

{% block title %}All Orders{% endblock title %}

{% block body %}
<section class="bg-secondary" style="height: 200px;">

</section>
<div class="card shadow-lg border-0 bg-light m-5 p-5">
    <div class="row">
        <div class="col-md-12">
            <h3>All Orders</h3>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Order ID</th>
                        <th>Customer</th>
                        <th>Ordered On</th>
                        <th>Amount</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    {% for order in allorders %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td><a href="{% url 'ecommerceapp:adminorderdetail' order.id %}">#ORDER_{{order.id}}</a></td>
                        <td>{{order.ordered_by}}</td>
                        <td>{{order.created_at}}</td>
                        <td>NGN.{{order.total}}</td>
                        <td>{{order.order_status}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock body %}

templates/adminpages/adminproductcreate.html
{% extends "adminpages/adminbase.html" %}
{% block title %}Add New Product{% endblock title %}

{% block body %}
<section class="bg-secondary" style="height: 200px;">

</section>
<div class="card shadow-lg border-0 bg-light m-5 p-5">
    <div class="row">
        <div class="card border-0 col-md-10 mx-auto">
            <h3>Add New Product</h3>
            <hr>
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{form.as_p}}
                <button class="btn btn-success">Submit Data</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/adminpages/adminproductlist.html
{% extends "adminpages/adminbase.html" %}
{% block title %}All Products{% endblock title %}

{% block body %}
<section class="bg-secondary" style="height: 200px;">

</section>
<div class="card shadow-lg border-0 bg-light m-5 p-5">
    <div class="row">
        <div class="col-md-12">
            <h3>All Product List</h3><hr>
            <a href="{% url 'ecommerceapp:adminproductcreate' %}">Add New Product</a>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Product Title</th>
                        <th>Image</th>
                        <th>Price</th>
                        <th>Views</th>
                    </tr>
                </thead>
                <tbody>
                    {% for p in allproducts %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{p.title}}</td>
                        <td><img src="{{p.image.url}}" style="height: 60px;" alt=""></td>
                        <td>{{p.selling_price}}</td>
                        <td>{{p.view_count}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock body %}