ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("ecommerceapp.urls")),
    path('captcha/', include('captcha.urls')),  # Add this

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerceapp/urls.py
from django.urls import path
from .views import *
from . import views


app_name = "ecommerceapp"

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("about/", AboutView.as_view(), name="about"),
    path("contact/", ContactView.as_view(), name="contact"),
    path("shops/", ShopsView.as_view(), name="shops"),
    path("product/<slug:slug>", ProductDetailView.as_view(), name="productdetail"),

    path("addtocart/<int:pro_id>/", AddToCartView.as_view(), name="addtocart"),
    path("my-cart/", MyCartView.as_view(), name="mycart"),
    path("manage-cart/<int:cp_id>/", ManageCartView.as_view(), name="managecart"),
    path("empty-cart/", EmptyCartView.as_view(), name="emptycart"),

    path("checkout/", CheckoutView.as_view(), name="checkout"),
    path("paystack-request/<int:order_id>/", PaystackRequestView.as_view(), name="paystackrequest"),
    path("paystack-webhook/", PaystackWebhookView.as_view(), name="paystack-webhook"),
    path("paystack-verify/", PaystackVerifyView.as_view(), name="paystack-verify"),

    path("register/", CustomerRegistrationView.as_view(), name="customerregistration"),
    
    path("logout/", CustomerLogoutView.as_view(), name="customerlogout"),
    path("login/", CustomerLoginView.as_view(), name="customerlogin"),


    path("profile/", CustomerProfileView.as_view(), name="customerprofile"),
    path("profile/order-<int:pk>/", CustomerOrderDetailView.as_view(), name="customerorderdetail"),
    
    path("profile/edit/", CustomerProfileEditView.as_view(), name="customerprofile_edit"),

    path('change_password/', views.change_password, name='change_password'),


    path("search/", SearchView.as_view(), name="search"),

    path("forgot-password/", PasswordForgotView.as_view(), name="passwordforgot"),
    path("password-reset/<email>/<token>/", PasswordResetView.as_view(), name="passwordreset"),

    # Admin Side pages

    path("admin-login/", AdminLoginView.as_view(), name="adminlogin"),
    path("admin-home/", AdminHomeView.as_view(), name="adminhome"),
    path("admin-order/<int:pk>/", AdminOrderDetailView.as_view(), name="adminorderdetail"),
    path("admin-all-orders/", AdminOrderListView.as_view(), name="adminorderlist"),

    path("admin-order/<int:pk>-change/", AdminOrderStatusChangeView.as_view(), name="adminorderstatuschange"),

    path("admin-product/list/", AdminProductListView.as_view(), name="adminproductlist"),
    path("admin-product/add/", AdminProductCreateView.as_view(), name="adminproductcreate"),
]

ecommerceapp/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Contact(models.Model):
    name=models.CharField(max_length=50)
    email=models.EmailField()
    phonenumber=models.IntegerField()
    desc=models.TextField(max_length=500)
   
    def __str__(self):
        return self.name

class Admin(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=50)
    image = models.ImageField(upload_to='admins')
    mobile = models.CharField(max_length=20)

    def __str__(self):
        return self.user.username
    

class Customer(models.Model):
   user = models.OneToOneField(User, on_delete=models.CASCADE, related_name = 'customer', null=True, blank=True)
   full_name = models.CharField(max_length=200)
   address = models.CharField(max_length=200, null=True, blank=True)
   joined_on = models.DateTimeField(auto_now_add=True)

   def __str__(self):
       return self.full_name 

class Category(models.Model):
    title = models.CharField(max_length=200)
    slug = models. SlugField(unique=True)

    def __str__(self):
        return self.title




class Product(models.Model):
    VARIANT_CHOICES = (
        ('None', 'None'),
        ('Size', 'Size'),
        ('Color', 'Color'),
        ('Size-Color', 'Size-Color'),
    )

    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="products/")
    marked_price = models.PositiveIntegerField()
    selling_price = models.PositiveIntegerField()
    description = models.TextField()
    view_count = models.PositiveIntegerField(default=0)
    variant = models.CharField(max_length=20, choices=VARIANT_CHOICES, default='None')

    def __str__(self):
        return self.title
    
class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    images = models.ImageField(upload_to="products/images/")

    def __str__(self):
        return self.product.title
    




class Cart(models.Model):
    customer = models.ForeignKey(
        Customer, on_delete=models.SET_NULL, null=True, blank=True)
    total = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "Cart: " + str(self.id)
    

class CartProduct(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, related_name="cartproducts")
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    rate = models.PositiveIntegerField()
    color = models.CharField(max_length=50, blank=True, null=True)  # Add this line
    size = models.CharField(max_length=50, blank=True, null=True)   # Add this line

    quantity = models.PositiveIntegerField()
    subtotal = models.PositiveIntegerField()

    def __str__(self):
        return f"Cart: {self.cart.id} CartProduct: {self.id}"

ORDER_STATUS = (
    ("Order Received", "Order Received"),
    ("Order Processing", "Order Processing"),
    ("On the way", "On the way"),
    ("Order Completed", "Order Completed"),
    ("Order Canceled", "Order Canceled"),
)


CURRENCY_CHOICES = [
    ('USD', 'Dollar'),
    ('EUR', 'Euro'),
    ('NGN', 'Naira'),
    ('CAD', 'Canadian Dollar'),
    ('AUD', 'Australian Dollar'),
]


class Order(models.Model):
    cart = models.OneToOneField(Cart, on_delete=models.CASCADE)
    ordered_by = models.CharField(max_length=200)
    email = models.EmailField(null=True, blank=True)
    shipping_address = models.CharField(max_length=200)
    mobile = models.CharField(max_length=10)
    subtotal = models.PositiveIntegerField()
    discount = models.PositiveIntegerField()
    total = models.PositiveIntegerField()
    order_status = models.CharField(max_length=50, choices=ORDER_STATUS)
    created_at = models.DateTimeField(auto_now_add=True)
    payment_completed = models.BooleanField(default=False, null=True, blank=True)
    currency = models.CharField(max_length=3, choices=CURRENCY_CHOICES, default='NGN')
    paystack_reference = models.CharField(max_length=100, blank=True, null=True)
    order_status = models.CharField(max_length=50, default='Order Received')

    def __str__(self):
        return "Order: " + str(self.id)
    

templates/addtocart.html
{% extends "base.html" %}

{% block title %} Product Added to Cart Successfully {% endblock title %}

{% block body %}
<section class="bg-secondary" style="height: 200px;">

</section>
<div class="card shadow-lg border-0 m-5 p-5">
    <h1>Product Added to Cart</h1>
    <p>The product "{{ product.title }}" has been added to your cart successfully.</p>

    <p>Color: {{ color }}</p>
    <p>Size: {{ size }}</p>
    <p>Price: NGN {{ product.selling_price }}</p>
    <p>Total: NGN {{ cart.total }}</p>
    <a href="{% url 'ecommerceapp:mycart' %}" class="btn btn-success">View Cart</a>
    <a href="{% url 'ecommerceapp:shops' %}" class="btn btn-secondary">Continue Shopping</a>
</div>
{% endblock body %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <title>
    {% block title %} {% endblock title %}
  </title>
  <meta content="ecommerce website we deliver products in 1 hours" name="description">
  <meta content="ecommerce" name="amazon,flipkart,selling,products">


  <!-- Google Fonts -->
  <link
    href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
    rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static '/assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static '/assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static '/assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static '/assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static '/assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static '/assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static '/assets/css/style.css' %}" rel="stylesheet">
  
  <link rel="stylesheet" href="{% static 'css/index.css' %}">
  {% block style %}{% endblock style %}

</head>

<body>

  <!-- ======= Header ======= -->
   
  <header id="header" class="fixed-top bg-dark">


    <div class="container-fluid d-flex align-items-center justify-content-between">

      <a class="navbar-brand fs-3 fw-bold text-light" href="{% url 'ecommerceapp:index' %}" class="logo text-white p-3">YARN_ME<span class="text-success fw.bold">.</span></a>


      <nav id="navbar" class="navbar navbar-expand-lg">
        <ul class="px-3">
          <li class="nav-item!"><a class="nav-link scrollto active mx-3" href="{% url 'ecommerceapp:index' %}">Home</a></li>
          <li class="nav-item"><a class="nav-link scrollto mx-3" href="{% url 'ecommerceapp:shops' %}">Shop</a></li>
          <li class="nav-item"><a class="nav-link scrollto mx-3" href="{% url 'ecommerceapp:about' %}">About</a></li>


          {% comment %} <li><a class="nav-link scrollto bg-danger p-3 m-2" href="/contact">Cart</a></li> {% endcomment %}


          <li class="nav-item"><a class="nav-link scrollto mx-3" href="{% url 'ecommerceapp:contact' %}">Contact</a></li>
          <li class="nav-item"><a class="nav-link scrollto mx-3" href="{% url 'ecommerceapp:mycart' %}">View Cart</a></li>

          <li class="dropdown">
            {% if request.user.customer %}
            <li class="text-success">Welcome <span class="fw-bold">{{request.user.username}}!</span></li>
            <li><a href="{% url 'ecommerceapp:customerprofile' %}">My Profile</a></li>
            <li><a  class="bg-black text-white p-3 m-2" href="{% url 'ecommerceapp:customerlogout'  %}">Logout</a></li>
            {% else %}
              <a class="nav-link scrollto mx-3" href="#">SignIn<i class="bi bi-chevron-down mx-3"></i></a>

            <ul>
              <li><a href="{% url 'ecommerceapp:customerregistration' %}">Register</a></li>
            
              <li><a href="{% url 'ecommerceapp:customerlogin' %}">Login</a></li>
            </ul>
          </li>
          
          {% endif %}
          
          <form class="ms-4 d-flex" role="search" action="{% url 'ecommerceapp:search' %}" method="GET">
            <input class="form-control me-2" type="search" name="keyword" placeholder="Search" aria-label="Search" required>
            <button class="btn bg-success" type="submit">Search</button>
          </form>
        </ul>
        
             

        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->
    </div>
    
  </header><!-- End Header -->""

  <!-- ======= Hero Section ======= -->
  {% comment %} <section id="hero" class="min-vh-100 d-flex align-items-center justify-content-center">
    <div class="hero-container">

      {% block content %}






      {% endblock content %}

    </div>
  </section><!-- End Hero --> {% endcomment %}

  <main id="main">

    {% block body %}







    {% endblock body %}

  </main><!-- End #main -->

 <!-- ======= Footer ======= -->
 <footer id="footer">

  <div class="footer-top">
    <div class="container my-auto">
      <div class="row">

        <div class="col-lg-3 footer-contact">
          <h3>Yarn_me</h3>
          <p>
            <strong>Phone:</strong> +2347054658283<br>
            <strong>Email:</strong> yarnmenigeria@gmail.com<br>
          </p>
        </div>

        <div class="col-lg-3 footer-links">
          <h4>Useful Links</h4>
          <ul>
            <li><i class="bx bx-chevron-right"></i> <a href="{% url 'ecommerceapp:index' %}">Home</a></li>
            <li><i class="bx bx-chevron-right"></i> <a href="{% url 'ecommerceapp:shops' %}">Shop</a></li>
            <li><i class="bx bx-chevron-right"></i> <a href="{% url 'ecommerceapp:about' %}">About</a></li>
            <li><i class="bx bx-chevron-right"></i> <a href="#">Terms of service</a></li>
            <li><i class="bx bx-chevron-right"></i> <a href="#">Privacy policy</a></li>
          </ul>
        </div>

        <div class="col-lg-3 footer-newsletter">
          <h4>Join Our Newsletter</h4>
          <form action="" method="post">
            <input type="email" name="email"><input type="submit" class="bg-success" value="Subscribe">
          </form>
        </div>

      </div>
    </div>
  </div>

  <div class="container-fluid d-md-flex py-4 bg-dark">

    <div class="container me-md-auto text-center text-md-start">
      <div class="copyright">
        &copy; Copyright <strong><span>Yarn_me</span></strong>. All Rights Reserved
      </div>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/tempo-free-onepage-bootstrap-theme/ -->
        Designed by <a href="/">Gucci</a>
      </div>
    </div>
    <div class="social-links text-center text-md-right pt-3 pt-md-0 mx-5">
      <a href="https://www.x.com/yarnmenigeria" class="twitter"><i class="bx bxl-twitter"></i></a>
      <a href="https://www.instagram.com/yarn_me.ng" class="instagram"><i class="bx bxl-instagram"></i></a>
      <a href="https://wa.me/message/QLA5SV6JSJJ2J1" class="whatsapp"><i class="bx bxl-whatsapp"></i></a>
    </div>
  </div>
</footer><!-- End Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
      class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static '/assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static '/assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static '/assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static '/assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static '/assets/vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static '/assets/js/main.js' %}"></script>


  {% block script %}

  {% endblock script %}

</body>

</html>

templates/customerprofile.html
{% extends "base.html" %}

{% block title %}My Profile{% endblock title %}

{% block body %}
<section class="bg-secondary" style="height: 200px;"></section>

<div class="container mt-5">
    <div class="row">
        <!-- Sidebar -->
        <div class="col-md-3">
            <div class="card border-0 shadow-lg bg-light text-white" style="height: 400px;">
                <div class="card-body">
                    <h4 class="card-title text-success fw-bold py-4">Account Settings</h4>

                    <div id="simple-list-example" class="simple-list-example-scrollspy text-secondary">
                        <a class="list-group-item list-group-item-action py-3" href="#list-item-1">Customer Information</a>
                        <a class="list-group-item list-group-item-action py-3" href="{% url 'ecommerceapp:customerprofile_edit' %}">Edit Profile</a>
                        <a class="list-group-item list-group-item-action py-3" href="#list-item-3">Previous Orders</a>
                        <a class="list-group-item list-group-item-action py-3" href="{% url 'ecommerceapp:change_password' %}">Change Password</a>
                    </div> 
                  
                </div>
            </div>
        </div>

        <!-- Main Content -->
        <div class="col-md-9">
            <!-- Customer Information Section -->
            <div data-bs-spy="scroll" data-bs-target="#simple-list-example" data-bs-offset="0" data-bs-smooth-scroll="true" class="scrollspy-example" tabindex="0">
                <div class="card border-0 shadow-lg">
                    <div class="card-header bg-secondary text-white">
                        <h3 id="list-item-1">Customer Information</h3>
                    </div>
                    <div class="card-body bg-light text-dark">
                        <p class="font-weight-bold text-success">Name:</p>
                        <p class="border p-2 rounded bg-grey text-dark">{{ customer.full_name }}</p>
                        
                        <p class="font-weight-bold text-success">Username:</p>
                        <p class="border p-2 rounded bg-grey text-dark">{{ customer.user.username }}</p>
                        
                        <p class="font-weight-bold text-success">Email:</p>
                        <p class="border p-2 rounded bg-grey text-dark">{{ customer.user.email }}</p>
                        
                        <p class="font-weight-bold text-success">Address:</p>
                        <p class="border p-2 rounded bg-grey text-dark">{{ customer.address }}</p>
                        
                        <p class="font-weight-bold text-success">Joined on:</p>
                        <p class="border p-2 rounded bg-grey text-dark">{{ customer.joined_on }}</p>
                    </div>
                </div>
            </div>


            

            <!-- Previous Orders Section -->
            <div id="previous-orders" class="my-5 bg-dark">
                <div class="card border-0 border-0 shadow-lg p-4">
                    <div class="card-header bg-secondary text-white">
                        <h3 id="list-item-3">Previous Orders</h3>
                    </div>
                    <div class="card-body bg-light">
                        <table class="table table-striped table-bordered">
                            <thead class="bg-success text-white">
                                <tr>
                                    <th>SN</th>
                                    <th>Order ID</th>
                                    <th>Amount</th>
                                    <th>Ordered on</th>
                                    <th>Status</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for ord in orders %}
                                <tr>
                                    <td>{{ forloop.counter }}</td>
                                    <td><a class="text-success" href="{% url 'ecommerceapp:customerorderdetail' ord.pk %}">#ORDER_{{ ord.id }}</a></td>
                                    <td>NGN {{ ord.total }}</td>
                                    <td>{{ ord.created_at|timesince }} ago</td>
                                    <td><span class="badge badge-success text-success">{{ ord.order_status }}</span></td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock body %}

templates/index.html
{% extends "base.html" %}
{% load static %}

{% block title %}
Home
{% endblock title %}


{% block body %}
<main id="main">

    <section id="hero" class="min-vh-100 d-flex align-items-center justify-content-center">
        <div class="hero-container">
            <h1 class="text-white fw-semibold display-1">WELCOME TO <strong>YARN_ME</strong></h1>
            <h5 class="text-white mt-3 mb-4">… IN A HEARTBEAT THREADS OF FIBER ARE YARNED INTO PERFECTION, JUST FOR YOU.</h5>
            <a href="#about" class="btn-get-started scrollto text-decoration-none">Get Started</a>
            <a href="{% url 'ecommerceapp:shops' %}" class="btn-get-started scrollto text-decoration-none mt-2">Shop Now</a>
        </div>
    </section>

        <div class="card shadow-lg border-0 m-5 p-5">
            <h2 class="fw-bold">Products</h2>
            <hr>
            <div class="row">
                {% for p in product_list %}
                <div class="col-md-3 card">
                    <div class="card-body">
                        <img src="{{ p.image.url }}" alt="" class="img-fluid" style="height: 200px; object-fit: contain;">
                        <h4><a href="{% url 'ecommerceapp:productdetail' p.slug %}">{{ p.title }}</a></h4>
                        <p class="card-text">{{ p.description }}</p>
                        <h6 class="card-title mb-3">Price: <strike>#{{ p.marked_price }}</strike> #{{ p.selling_price }}</h6>
        
                        <form action="{% url 'ecommerceapp:addtocart' p.id %}" method="GET">
                            {% csrf_token %}
                            <!-- Include variant selection if applicable -->
                            {% if p.variant == 'Size-Color' or p.variant == 'Color' %}
                            <div class="form-group">
                                <label for="color">Color:</label>
                                <input type="text" name="color" id="color" class="form-control" placeholder="Enter color">
                            </div>
                            {% endif %}
                            {% if p.variant == 'Size-Color' or p.variant == 'Size' %}
                            <div class="form-group">
                                <label for="size">Size:</label>
                                <input type="text" name="size" id="size" class="form-control" placeholder="Enter size">
                            </div>
                            {% endif %}
                            <button type="submit" class="btn btn-secondary w-100 py-2">Add To Cart</button>
                        </form>
                    </div>
                </div>
                {% endfor %}
            </div>
            <nav aria-label="...">
                <ul class="pagination">
                    {% if product_list.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ product_list.previous_page_number }}">Previous</a>
                    </li>
                    {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="" tabindex="-1">Previous</a>
                    </li>
                    {% endif %}

                    {% for i in product_list.paginator.page_range %}
                    {% if i == product_list.number %}
                    <li class="page-item active"><a class="page-link">{{i}}</a></li>
                    {% else %}
                    <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
                    {% endif %}
                    {% endfor %}

                    {% if product_list.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ product_list.next_page_number }}">Next</a>
                    </li>
                    {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="" tabindex="-1">Next</a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
        </div>
</main><!-- End #main -->

{% endblock body %}

templates/mycart.html
<!-- mycart.html -->
{% extends "base.html" %}

{% block title %} My cart {% endblock title %}

{% block body %}
<section class="bg-secondary" style="height: 200px;">

</section>
<div class="card shadow-lg border-0 m-5 p-5">
    <div class="row">
        <div class="col-md-8">
            <h4 class="py-3">Items in my cart</h4><hr>
            <table class="table">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Product</th>
                        <th>Color</th>
                        <th>Size</th>
                        <th>Rate</th>
                        <th>Quantity</th>
                        <th>Subtotal</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cp in cart.cartproducts.all %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ cp.product.title }}</td>
                        <td>{{ cp.color }}</td>
                        <td>{{ cp.size }}</td>
                        <td>#{{ cp.rate }}</td>
                        <td>{{ cp.quantity }}</td>
                        <td>#{{ cp.subtotal }}</td>
                        <td>
                            <a href="{% url 'ecommerceapp:managecart' cp.id %}?action=inc" class="btn btn-success"> + </a>
                            <a href="{% url 'ecommerceapp:managecart' cp.id %}?action=dcr" class="btn btn-warning"> - </a>
                            <a href="{% url 'ecommerceapp:managecart' cp.id %}?action=rmv" class="btn btn-danger"> * </a>
                        </td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <th colspan="6" class="text-right">Total:</th>
                        <th>#{{ cart.total }}</th>
                        {% if cart.cartproducts.all %}
                        <th><a href="{% url 'ecommerceapp:emptycart' %}">Empty Cart</a></th>
                        {% endif %}
                    </tr>
                    {% if cart.cartproducts.all %}
                    <tr>
                        <th><a class="btn btn-success" href="{% url 'ecommerceapp:checkout' %}">Checkout</a></th>
                    </tr>
                    {% endif %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock body %}

templates/search.html
{% extends "base.html" %}

{% block title %}Search{% endblock title %}
{% block body %}
<section class="bg-secondary" style="height: 200px;">

</section>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h3>Search Results for<span class="text-secondary"> "{{request.GET.keyword}}"</span></h3>
            <hr>
            {% for result in results %}
            <div class="row">
                <div class="col-md-4">
                    <img src="{{result.image.url}}" class="img-fluid" alt="">
                </div>
                <div class="col-md-8">
                    <h4><a href="{% url 'ecommerceapp:productdetail' result.slug %}">{{result.title}}</a></h4>
                    <p>{{result.description|truncatechars:50}}</p>
                    <a class="btn btn-secondary py-2" href="{% url 'ecommerceapp:addtocart' result.id %}">Add To Cart</a>

                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock body %}

templates/shops.html
<!-- shop.html -->
{% extends "base.html" %}

{% block title %}
    Shops
{% endblock title %}

{% block body %} 
<section class="bg-secondary" style="height: 200px;">

</section>
<div class="card shadow-lg border-0 m-5 p-5">
    <h2 class="fw-bold">All Products</h2>
    <a href="/" class="text-decoration-none"><h5>Home / </a> Products</h5><hr>
    {% for cat in allcategories %}
    <h4 class="fw-medium">{{ cat.title }}</h4><hr>
    <div class="row">
        {% for p in cat.product_set.all %}
        <div class="col-md-3 card">
            <div class="card-body">
                <img src="{{ p.image.url }}" alt="" class="img-fluid" style="height: 200px; object-fit: contain;">
                <h4><a href="{% url 'ecommerceapp:productdetail' p.slug %}">{{ p.title }}</a></h4>
                <p class="card-text">{{ p.description }}</p>
                <h6 class="card-title mb-3">Price: <strike>#{{ p.marked_price }}</strike> #{{ p.selling_price }}</h6>

                <form action="{% url 'ecommerceapp:addtocart' p.id %}" method="GET">
                    {% csrf_token %}
                    <!-- Include variant selection if applicable -->
                    {% if p.variant == 'Size-Color' or p.variant == 'Color' %}
                    <div class="form-group">
                        <label for="color">Color:</label>
                        <input type="text" name="color" id="color" class="form-control" placeholder="Enter color">
                    </div>
                    {% endif %}
                    {% if p.variant == 'Size-Color' or p.variant == 'Size' %}
                    <div class="form-group">
                        <label for="size">Size:</label>
                        <input type="text" name="size" id="size" class="form-control" placeholder="Enter size">
                    </div>
                    {% endif %}
                    <button type="submit" class="btn btn-secondary w-100 py-2">Add To Cart</button>
                </form>
            </div>
        </div>
        {% endfor %}
    </div>
    {% endfor %}
</div>
{% endblock body %}